# Generated by Django 2.0.7 on 2018-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date joined')),
                ('git_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_penalized', models.DateTimeField()),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Spring'), (2, 'Fall')])),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
