# Generated by Django 2.0.7 on 2018-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intro', models.CharField(max_length=200)),
                ('b_day', models.DateField()),
                ('lang', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='date joined')),
                ('github_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
